###
GET http://localhost:3000/
Cookie: name1=value1; name2=value2; name3=value3
Accept-Encoding: gzip, deflate, br
###
GET http://localhost:3000/book
Accept-Encoding: *
###
GET http://localhost:3000/router1/routerA
###
PATCH http://localhost:3000/router1/routerA/1?user=1&user=2&user=3&group=b
Content-Type: application/json

{"user":"name","pass":"word"}