###
GET http://localhost:5555/
###
GET http://localhost:5555/?u=1&u=2&p=1
Cookie: name1=value1; name2=value2; name3=value3
###
PATCH http://localhost:5555/router1/routerB/1?u=1&u=2&p=1
Cookie: name1=value1; name2=value2; name3=value3
Content-Type: application/json

{"user":"name","pass":"word"}